# Generated by Django 5.1.4 on 2025-01-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('state', models.BooleanField(default=False)),
                ('time_of_completion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
